---
abstract: 'The great new oxdPerl!'
author:
  - 'Gaurav Chhabra <gaurav.chhabra6785@gmail.com>'
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0
dynamic_config: 1
generated_by: 'Module::Build version 0.4003, CPAN::Meta::Converter version 2.133380'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: oxdPerl
provides:
  oxdPerl:
    file: lib/oxdPerl.pm
    version: 0.01
version: 0.01
